improve emonsd detection

diff --git a/emoncmsupdate b/emoncmsupdate
--- a/emoncmsupdate
+++ b/emoncmsupdate
@@ -7,9 +7,8 @@ echo "Emoncms update script V1.2.1 (6th Feb 2019)"
 date
 echo "==========================================="
 echo
-username="trystan"
-userpi=0
-env_pi=1
+username="pi"
+homedir="/home/$username"
 
 echo "username: $username"
 echo
@@ -17,19 +16,22 @@ echo
 echo "Checking environment:"
 
 # Check that specified user directory exists
-if [ -d /home/$username ]; then 
-    echo "- User directory /home/$username found"
-    if [ "$username" = "pi" ]; then
-        userpi=1
-    fi
+if [ -d $homedir ]; then 
+    echo "- User directory $homedir found"
 else 
-    echo "- User directory /home/$username not found (please ammend username)"
+    echo "- User directory $homedir not found (please ammend username)"
     exit 0
 fi
 
-if ! [ "$userpi" = "1" ]; then
-    echo "- No pi user directory, unlikely a pi"
-    env_pi=0
+emonSD_pi_env=0
+# Check for pi user
+pi=$(id -u pi)
+if [ $pi ] && [ -d /home/pi ]; then
+  echo "- pi user and pi user directory found"
+  emonSD_pi_env=1
+else 
+  echo "- could not find pi user or pi user directory"
+  emonSD_pi_env=0
 fi
 
 # Check emonSD version
@@ -37,19 +39,16 @@ image_version=$(ls /boot | grep emonSD)
 
 if [ "$image_version" = "" ]; then
     echo "- Could not find emonSD version file"
-    image_version=0
-    env_pi=0
+    emonSD_pi_env=0
 else 
     echo "- emonSD version: $image_version"
 fi
 
-if [ "$env_pi" = "0" ]; then
-    echo "- Assuming non pi install"
+if [ "$emonSD_pi_env" = "0" ]; then
+    echo "- Assuming non emonSD install"
 fi
 
 # Check emoncms directory
-
-
 if [ -d /var/www/emoncms ]; then
     emoncms_dir="/var/www/emoncms"
 else
@@ -60,7 +59,6 @@ else
         exit 0
     fi
 fi
-
 echo "- emoncms directory: $emoncms_dir"
 
 echo
@@ -79,13 +77,13 @@ if [ "$uid" = "0" ] ; then
 fi
 
 #########################################################################################
-if [ "$env_pi" = "1" ]; then 
+if [ "$emonSD_pi_env" = "1" ]; then 
 
     # Install sudoers entry to enable emoncms reboot button
     if [ ! -f /etc/sudoers.d/emoncms-rebootbutton ]; then
         # double check correct sudo syntax
-        sudo visudo -cf /home/$username/emonpi/emoncms-rebootbutton && \
-        sudo cp /home/$username/emonpi/emoncms-rebootbutton /etc/sudoers.d/
+        sudo visudo -cf $homedir/emonpi/emoncms-rebootbutton && \
+        sudo cp $homedir/emonpi/emoncms-rebootbutton /etc/sudoers.d/
         sudo chmod 0440 /etc/sudoers.d/emoncms-rebootbutton
         echo
         echo "Install emonPi Emoncms admin reboot button sudoers entry"
@@ -96,8 +94,8 @@ if [ "$env_pi" = "1" ]; then
 
     if [ ! -f /etc/sudoers.d/emoncms-filesystem ]; then
         # double check correct sudo syntax
-        sudo visudo -cf /home/$username/emonpi/emoncms-filesystem && \
-        sudo cp /home/$username/emonpi/emoncms-filesystem /etc/sudoers.d/
+        sudo visudo -cf $homedir/emonpi/emoncms-filesystem && \
+        sudo cp $homedir/emonpi/emoncms-filesystem /etc/sudoers.d/
         sudo chmod 0440 /etc/sudoers.d/emoncms-filesystem
         echo
         echo "emonPi Emoncms admin file-system toggle buttons sudoers entry installed"
@@ -108,8 +106,8 @@ fi
 
 if [ ! -f /etc/sudoers.d/emonhub-sudoers ]; then
     # double check correct sudo syntax
-    sudo visudo -cf /home/$username/emonpi/emonhub-sudoers && \
-    sudo cp /home/$username/emonpi/emonhub-sudoers /etc/sudoers.d/
+    sudo visudo -cf $homedir/emonpi/emonhub-sudoers && \
+    sudo cp $homedir/emonpi/emonhub-sudoers /etc/sudoers.d/
     sudo chmod 0440 /etc/sudoers.d/emonhub-sudoers
     echo
     echo "emonhub service control sudoers entry installed"
@@ -120,8 +118,8 @@ fi
 
 if [ ! -f /etc/sudoers.d/emoncms-setup-sudoers ]; then
     # double check correct sudo syntax
-    sudo visudo -cf /home/$username/emonpi/emoncms-setup/emoncms-setup-sudoers && \
-    sudo cp /home/$username/emonpi/emoncms-setup/emoncms-setup-sudoers /etc/sudoers.d/
+    sudo visudo -cf $homedir/emonpi/emoncms-setup/emoncms-setup-sudoers && \
+    sudo cp $homedir/emonpi/emoncms-setup/emoncms-setup-sudoers /etc/sudoers.d/
     sudo chmod 0440 /etc/sudoers.d/emoncms-setup-sudoers
     echo
     echo "Emoncms setup module sudoers entry installed"
@@ -131,17 +129,17 @@ fi
 
 # Setup user group to enable reading GPU temperature (pi only)
 #https://github.com/emoncms/emoncms/pull/869
-if [ "$env_pi" = "1" ]; then 
+if [ "$emonSD_pi_env" = "1" ]; then 
     sudo usermod -G video www-data
 fi
 
 #########################################################################################
 # Record current state of emoncms settings.php
 echo
-current_settings_md5="$(/home/$username/emonpi/./md5sum.py $emoncms_dir/settings.php)"
+current_settings_md5="$($homedir/emonpi/./md5sum.py $emoncms_dir/settings.php)"
 echo "current settings.php md5: $current_settings_md5"
 
-current_default_settings_md5="$(/home/$username/emonpi/md5sum.py $emoncms_dir/default.emonpi.settings.php)"
+current_default_settings_md5="$($homedir/emonpi/md5sum.py $emoncms_dir/default.emonpi.settings.php)"
 echo "Default settings.php md5: $current_default_settings_md5"
 
 #########################################################################################
@@ -165,7 +163,7 @@ fi
 #########################################################################################
 # check to see if user has modifed settings.php and if update is need. Auto apply of possible
 echo
-new_default_settings_md5="$(/home/$username/emonpi/md5sum.py $emoncms_dir/default.emonpi.settings.php)"
+new_default_settings_md5="$($homedir/emonpi/md5sum.py $emoncms_dir/default.emonpi.settings.php)"
 echo "NEW default settings.php md5: $new_default_settings_md5"
 
 if [ "$current_default_settings_md5" == "$current_settings_md5" ]; then
@@ -201,24 +199,28 @@ for M in $emoncms_dir/Modules/*; do
     echo "------------------------------------------"
     echo "Updating $M module"
     echo "------------------------------------------"
+    
     branch=$(git -C $M branch | grep \* | cut -d ' ' -f2)
     echo "- git branch: $branch"
-    changes=$(git -C $M diff-index --quiet HEAD --)
-    if $changes; then
+    tags=$(git -C $M describe --tags)
+    echo "- git tags: $tags"
+    
+    changes=$(git -C $M diff-index HEAD --)
+    if [ "$changes" = "" ]; then
         echo "- no local changes"
         echo "- running: git pull origin $branch"
         echo
         git -C $M pull origin $branch
     else
-        echo "- changes"
+        echo "- git status:"
+        echo
+        git -C $M status
+        echo
     fi
-    tags=$(git -C $M describe --tags)
-    echo "- git tags: $tags"
+    
     echo
   fi
 done
-
-exit 0
 
 # Update modules installed in the home/user folder
 for module in "postprocess" "sync" "backup"; do
@@ -226,19 +228,24 @@ for module in "postprocess" "sync" "backup"; do
   echo "------------------------------------------"
   echo "Updating $module module"
   echo "------------------------------------------"
-  if [ -d /home/$username/$module ]; then
-    cd /home/$username/$module
+  if [ -d $homedir/$module ]; then
+    cd $homedir/$module
     branch=$(git branch | grep \* | cut -d ' ' -f2)
     echo "- git branch: $branch"
-    changes=$(git diff-index --quiet HEAD --)
-    if $changes; then
+    tags=$(git describe --tags)
+    echo "- git tags: $tags"
+    changes=$(git diff-index HEAD --)
+    if [ "$changes" = "" ]; then
         echo "- no local changes"
         echo "- running: git pull origin $branch"
         echo
         git pull origin $branch
-        # ln -sf /home/$username/$module/$module-module $emoncms_dir/Modules/$module
+        # ln -sf $homedir/$module/$module-module $emoncms_dir/Modules/$module
     else
-        echo "- changes"
+        echo "- git status:"
+        echo
+        git status
+        echo
     fi
   else
     echo "$module module does not exist"
@@ -269,13 +276,13 @@ done
 
 # Direct installation in Modules folder
 for module in "postprocess" "sync" "backup"; do
-  if ! [ -d /home/$username/$module ]; then
+  if ! [ -d $homedir/$module ]; then
     echo
     echo "- Installing Emoncms $module module https://github.com/emoncms/$module"
-    cd /home/$username
+    cd $homedir
     git clone https://github.com/emoncms/$module
-    ln -s /home/$username/$module/$module-module $emoncms_dir/Modules
-    cd /home/$username/$module/$module-module
+    ln -s $homedir/$module/$module-module $emoncms_dir/Modules
+    cd $homedir/$module/$module-module
     if [ `git branch --list stable` ]; then
        echo "-- git checkout stable"
        git checkout stable
@@ -289,13 +296,13 @@ echo
 #########################################################################################
 sudo service apache2 restart
 
-if [ "$env_pi" = "1" ]; then 
+if [ "$emonSD_pi_env" = "1" ]; then 
   # Install emoncms-setup module (symlink from emonpi repo)
-  if [ -d /home/$username/emonpi/emoncms-setup ] && [ ! -d $emoncms_dir/Modules/setup ]; then
+  if [ -d $homedir/emonpi/emoncms-setup ] && [ ! -d $emoncms_dir/Modules/setup ]; then
     echo "Installing emoncms/emonPi setup module: symlink from ~/emonpi/emoncms-setup"
-    ln -s /home/$username/emonpi/emoncms-setup $emoncms_dir/Modules/setup
+    ln -s $homedir/emonpi/emoncms-setup $emoncms_dir/Modules/setup
   else
-    if [ ! -d /home/$username/emonpi/emoncms-setup ]; then
+    if [ ! -d $homedir/emonpi/emoncms-setup ]; then
       echo "Cannot find emoncms-setup module, please update ~/emonpi repo"
     fi
   fi
@@ -380,11 +387,12 @@ echo "------------------------------------------"
 # echo "Copy new default.emonpi.settings.php to settings.php & make backup old.emonpi.settings.php"
 # sudo cp $emoncms_dir/settings.php $emoncms_dir/old.settings.php
 # sudo cp $emoncms_dir/default.emonpi.settings.php $emoncms_dir/settings.php
-if [ "$env_pi" = "1" ]; then 
-  echo "Update Emoncms database"
-  php /home/$username/emonpi/emoncmsdbupdate.php
-  echo
-fi
+
+#if [ "$emonSD_pi_env" = "1" ]; then 
+echo "Update Emoncms database"
+php $homedir/emonpi/emoncmsdbupdate.php
+echo
+#fi
 
 echo "Restarting Services..."
 if [ -d /lib/systemd/system ]; then
