- update all emoncms modules that have .git folder in emoncms/Modules folder - print git tags - allow for emoncms installed in both /var/www/emoncms and /var/www/html/emoncms directories

diff --git a/emoncmsupdate b/emoncmsupdate
--- a/emoncmsupdate
+++ b/emoncmsupdate
@@ -7,7 +7,7 @@ echo "Emoncms update script V1.2.1 (6th Feb 2019)"
 date
 echo "==========================================="
 echo
-username="pi"
+username="trystan"
 userpi=0
 env_pi=1
 
@@ -46,6 +46,22 @@ fi
 if [ "$env_pi" = "0" ]; then
     echo "- Assuming non pi install"
 fi
+
+# Check emoncms directory
+
+
+if [ -d /var/www/emoncms ]; then
+    emoncms_dir="/var/www/emoncms"
+else
+    if [ -d /var/www/html/emoncms ]; then
+        emoncms_dir="/var/www/html/emoncms"
+    else
+        echo "emoncms directory not found"
+        exit 0
+    fi
+fi
+
+echo "- emoncms directory: $emoncms_dir"
 
 echo
 uid=`id -u`
@@ -122,18 +138,18 @@ fi
 #########################################################################################
 # Record current state of emoncms settings.php
 echo
-current_settings_md5="$(/home/$username/emonpi/./md5sum.py /var/www/emoncms/settings.php)"
+current_settings_md5="$(/home/$username/emonpi/./md5sum.py $emoncms_dir/settings.php)"
 echo "current settings.php md5: $current_settings_md5"
 
-current_default_settings_md5="$(/home/$username/emonpi/md5sum.py /var/www/emoncms/default.emonpi.settings.php)"
+current_default_settings_md5="$(/home/$username/emonpi/md5sum.py $emoncms_dir/default.emonpi.settings.php)"
 echo "Default settings.php md5: $current_default_settings_md5"
 
 #########################################################################################
 
 # Pulling in latest Emoncms changes
 echo
-echo "Checking status of /var/www/emoncms git repository"
-cd /var/www/emoncms
+echo "Checking status of $emoncms_dir git repository"
+cd $emoncms_dir
 branch=$(git branch | grep \* | cut -d ' ' -f2)
 echo "- git branch: $branch"
 changes=$(git diff-index --quiet HEAD --)
@@ -149,7 +165,7 @@ fi
 #########################################################################################
 # check to see if user has modifed settings.php and if update is need. Auto apply of possible
 echo
-new_default_settings_md5="$(/home/$username/emonpi/md5sum.py /var/www/emoncms/default.emonpi.settings.php)"
+new_default_settings_md5="$(/home/$username/emonpi/md5sum.py $emoncms_dir/default.emonpi.settings.php)"
 echo "NEW default settings.php md5: $new_default_settings_md5"
 
 if [ "$current_default_settings_md5" == "$current_settings_md5" ]; then
@@ -164,7 +180,7 @@ fi
 if [ "$new_default_settings_md5" != "$current_default_settings_md5" ]; then
   echo "Update required to settings.php..."
   if [ $settings_unmodified == true ]; then
-    sudo cp /var/www/emoncms/default.emonpi.settings.php /var/www/emoncms/settings.php
+    sudo cp $emoncms_dir/default.emonpi.settings.php $emoncms_dir/settings.php
     echo "settings.php autoupdated"
   else
     echo "**ERROR: unable to autoupdate settings.php since user changes are present, manual review required**"
@@ -178,30 +194,31 @@ echo "=========================================="
 echo "UPDATING EMONCMS MODULES"
 echo "=========================================="
 echo
-# Update modules installed directly in the Modules folder
-for module in "nodes" "app" "config" "wifi" "dashboard" "graph" "device"; do
 
-  echo "------------------------------------------"
-  echo "Updating $module module"
-  echo "------------------------------------------"
-  if [ -d /var/www/emoncms/Modules/$module ]; then
-    cd /var/www/emoncms/Modules/$module
-    branch=$(git branch | grep \* | cut -d ' ' -f2)
+# Update modules installed directly in the Modules folder
+for M in $emoncms_dir/Modules/*; do
+  if [ -d "$M/.git" ]; then
+    echo "------------------------------------------"
+    echo "Updating $M module"
+    echo "------------------------------------------"
+    branch=$(git -C $M branch | grep \* | cut -d ' ' -f2)
     echo "- git branch: $branch"
-    changes=$(git diff-index --quiet HEAD --)
+    changes=$(git -C $M diff-index --quiet HEAD --)
     if $changes; then
         echo "- no local changes"
         echo "- running: git pull origin $branch"
         echo
-        git pull origin $branch
+        git -C $M pull origin $branch
     else
         echo "- changes"
     fi
-  else
-    echo "$module module does not exist"
+    tags=$(git -C $M describe --tags)
+    echo "- git tags: $tags"
+    echo
   fi
-  echo
 done
+
+exit 0
 
 # Update modules installed in the home/user folder
 for module in "postprocess" "sync" "backup"; do
@@ -219,7 +236,7 @@ for module in "postprocess" "sync" "backup"; do
         echo "- running: git pull origin $branch"
         echo
         git pull origin $branch
-        # ln -sf /home/$username/$module/$module-module /var/www/emoncms/Modules/$module
+        # ln -sf /home/$username/$module/$module-module $emoncms_dir/Modules/$module
     else
         echo "- changes"
     fi
@@ -236,11 +253,11 @@ echo "=========================================="
 
 # Direct installation in Modules folder
 for module in "graph" "device"; do
-  if ! [ -d /var/www/emoncms/Modules/$module ]; then
+  if ! [ -d $emoncms_dir/Modules/$module ]; then
     echo "- Installing Emoncms $module module https://github.com/emoncms/$module"
-    cd /var/www/emoncms/Modules
+    cd $emoncms_dir/Modules
     git clone https://github.com/emoncms/$module
-    cd /var/www/emoncms/Modules/$module
+    cd $emoncms_dir/Modules/$module
     if [ `git branch --list stable` ]; then
        echo "-- git checkout stable"
        git checkout stable
@@ -257,7 +274,7 @@ for module in "postprocess" "sync" "backup"; do
     echo "- Installing Emoncms $module module https://github.com/emoncms/$module"
     cd /home/$username
     git clone https://github.com/emoncms/$module
-    ln -s /home/$username/$module/$module-module /var/www/emoncms/Modules
+    ln -s /home/$username/$module/$module-module $emoncms_dir/Modules
     cd /home/$username/$module/$module-module
     if [ `git branch --list stable` ]; then
        echo "-- git checkout stable"
@@ -274,9 +291,9 @@ sudo service apache2 restart
 
 if [ "$env_pi" = "1" ]; then 
   # Install emoncms-setup module (symlink from emonpi repo)
-  if [ -d /home/$username/emonpi/emoncms-setup ] && [ ! -d /var/www/emoncms/Modules/setup ]; then
+  if [ -d /home/$username/emonpi/emoncms-setup ] && [ ! -d $emoncms_dir/Modules/setup ]; then
     echo "Installing emoncms/emonPi setup module: symlink from ~/emonpi/emoncms-setup"
-    ln -s /home/$username/emonpi/emoncms-setup /var/www/emoncms/Modules/setup
+    ln -s /home/$username/emonpi/emoncms-setup $emoncms_dir/Modules/setup
   else
     if [ ! -d /home/$username/emonpi/emoncms-setup ]; then
       echo "Cannot find emoncms-setup module, please update ~/emonpi repo"
@@ -318,7 +335,7 @@ done
 ################################################################################################
 for service in "emoncms_mqtt" "feedwriter" "service-runner"; do
 
-  if [ -d /etc/systemd ] && [ -f /var/www/emoncms/scripts/services/$service/$service.service ]; then
+  if [ -d /etc/systemd ] && [ -f $emoncms_dir/scripts/services/$service/$service.service ]; then
     if [ -f /etc/init.d/$service ]; then
       echo "removing initd $service service"
       sudo /etc/init.d/$service stop
@@ -348,7 +365,7 @@ for service in "emoncms_mqtt" "feedwriter" "service-runner"; do
     
     if [ ! -f /lib/systemd/system/$service.service ]; then
       echo "Installing $service.service in /lib/systemd/system (creating symlink)"
-      sudo ln -s /var/www/emoncms/scripts/services/$service/$service.service /lib/systemd/system
+      sudo ln -s $emoncms_dir/scripts/services/$service/$service.service /lib/systemd/system
       sudo systemctl enable $service.service
       sudo systemctl start $service.service
     else 
@@ -361,8 +378,8 @@ echo "------------------------------------------"
 ################################################################################################
 ## Don't overwrite settings unless required (un comment if required)
 # echo "Copy new default.emonpi.settings.php to settings.php & make backup old.emonpi.settings.php"
-# sudo cp /var/www/emoncms/settings.php /var/www/emoncms/old.settings.php
-# sudo cp /var/www/emoncms/default.emonpi.settings.php /var/www/emoncms/settings.php
+# sudo cp $emoncms_dir/settings.php $emoncms_dir/old.settings.php
+# sudo cp $emoncms_dir/default.emonpi.settings.php $emoncms_dir/settings.php
 if [ "$env_pi" = "1" ]; then 
   echo "Update Emoncms database"
   php /home/$username/emonpi/emoncmsdbupdate.php
