use for loops to install emoncms modules and services

diff --git a/emoncmsupdate b/emoncmsupdate
--- a/emoncmsupdate
+++ b/emoncmsupdate
@@ -1,83 +1,111 @@
 #!/bin/bash
 
 echo
-echo "================================="
+echo "==========================================="
 echo "Emoncms update started"
-echo "Emoncms update script V1.2.0"
-echo
-
+echo "Emoncms update script V1.2.1 (6th Feb 2019)"
 date
+echo "==========================================="
+echo
+username="pi"
+userpi=0
+env_pi=1
 
+echo "username: $username"
 echo
-#########################################################################################
-echo "#############################################################"
-echo
+
+echo "Checking environment:"
+
+# Check that specified user directory exists
+if [ -d /home/$username ]; then 
+    echo "- User directory /home/$username found"
+    if [ "$username" = "pi" ]; then
+        userpi=1
+    fi
+else 
+    echo "- User directory /home/$username not found (please ammend username)"
+    exit 0
+fi
+
+if ! [ "$userpi" = "1" ]; then
+    echo "- No pi user directory, unlikely a pi"
+    env_pi=0
+fi
+
 # Check emonSD version
 image_version=$(ls /boot | grep emonSD)
-echo "emonSD version: $image_version"
-echo
 
+if [ "$image_version" = "" ]; then
+    echo "- Could not find emonSD version file"
+    image_version=0
+    env_pi=0
+else 
+    echo "- emonSD version: $image_version"
+fi
+
+if [ "$env_pi" = "0" ]; then
+    echo "- Assuming non pi install"
+fi
+
+echo
 uid=`id -u`
 echo "EUID: $uid"
 
 if [ "$uid" = "0" ] ; then
-    # update is being ran mistakenly as root, switch to Pi user
-    echo "update running as root: switching to Pi user & restarting script"
+    # update is being ran mistakenly as root, switch to user
+    echo "update running as root: switching to $username user & restarting script"
     echo
     echo "**MANUAL SYSTEM REBOOT REQUIRED**"
     echo
-    echo "Please shutdown and reboot emonPi then run Update again"
-    su -c $0 pi
+    echo "Please reboot and run update again"
+    su -c $0 $username
     exit
 fi
 
 #########################################################################################
+if [ "$env_pi" = "1" ]; then 
 
-# Install sudoers entry to enable emoncms reboot button
+    # Install sudoers entry to enable emoncms reboot button
+    if [ ! -f /etc/sudoers.d/emoncms-rebootbutton ]; then
+        # double check correct sudo syntax
+        sudo visudo -cf /home/$username/emonpi/emoncms-rebootbutton && \
+        sudo cp /home/$username/emonpi/emoncms-rebootbutton /etc/sudoers.d/
+        sudo chmod 0440 /etc/sudoers.d/emoncms-rebootbutton
+        echo
+        echo "Install emonPi Emoncms admin reboot button sudoers entry"
+    fi
 
-if [ ! -f /etc/sudoers.d/emoncms-rebootbutton ]; then
-    # double check correct sudo syntax
-    sudo visudo -cf /home/pi/emonpi/emoncms-rebootbutton && \
-    sudo cp /home/pi/emonpi/emoncms-rebootbutton /etc/sudoers.d/
-    sudo chmod 0440 /etc/sudoers.d/emoncms-rebootbutton
-    echo
-    echo "Install emonPi Emoncms admin reboot button sudoers entry"
+    #########################################################################################
+    # Install sudoers entry to enable toggling file-system RO/RW mount via Emoncms admin
+
+    if [ ! -f /etc/sudoers.d/emoncms-filesystem ]; then
+        # double check correct sudo syntax
+        sudo visudo -cf /home/$username/emonpi/emoncms-filesystem && \
+        sudo cp /home/$username/emonpi/emoncms-filesystem /etc/sudoers.d/
+        sudo chmod 0440 /etc/sudoers.d/emoncms-filesystem
+        echo
+        echo "emonPi Emoncms admin file-system toggle buttons sudoers entry installed"
+    fi
 fi
-
 #########################################################################################
-
-# Install sudoers entry to enable toggling file-system RO/RW mount via Emoncms admin
-
-if [ ! -f /etc/sudoers.d/emoncms-filesystem ]; then
-    # double check correct sudo syntax
-    sudo visudo -cf /home/pi/emonpi/emoncms-filesystem && \
-    sudo cp /home/pi/emonpi/emoncms-filesystem /etc/sudoers.d/
-    sudo chmod 0440 /etc/sudoers.d/emoncms-filesystem
-    echo
-    echo "emonPi Emoncms admin file-system toggle buttons sudoers entry installed"
-fi
-
-#########################################################################################
-
 # Install sudoers entry to enable emonhub reboot button
 
 if [ ! -f /etc/sudoers.d/emonhub-sudoers ]; then
     # double check correct sudo syntax
-    sudo visudo -cf /home/pi/emonpi/emonhub-sudoers && \
-    sudo cp /home/pi/emonpi/emonhub-sudoers /etc/sudoers.d/
+    sudo visudo -cf /home/$username/emonpi/emonhub-sudoers && \
+    sudo cp /home/$username/emonpi/emonhub-sudoers /etc/sudoers.d/
     sudo chmod 0440 /etc/sudoers.d/emonhub-sudoers
     echo
-    echo "emonhub service constol sudoers entry installed"
+    echo "emonhub service control sudoers entry installed"
 fi
 
 #########################################################################################
-
 # Install sudoers entry for WiFI AP
 
 if [ ! -f /etc/sudoers.d/emoncms-setup-sudoers ]; then
     # double check correct sudo syntax
-    sudo visudo -cf /home/pi/emonpi/emoncms-setup/emoncms-setup-sudoers && \
-    sudo cp /home/pi/emonpi/emoncms-setup/emoncms-setup-sudoers /etc/sudoers.d/
+    sudo visudo -cf /home/$username/emonpi/emoncms-setup/emoncms-setup-sudoers && \
+    sudo cp /home/$username/emonpi/emoncms-setup/emoncms-setup-sudoers /etc/sudoers.d/
     sudo chmod 0440 /etc/sudoers.d/emoncms-setup-sudoers
     echo
     echo "Emoncms setup module sudoers entry installed"
@@ -85,37 +113,44 @@ fi
 
 #########################################################################################
 
-# Setup user group to enable reading pi GPU temperature
+# Setup user group to enable reading GPU temperature (pi only)
 #https://github.com/emoncms/emoncms/pull/869
-
-sudo usermod -G video www-data
-
+if [ "$env_pi" = "1" ]; then 
+    sudo usermod -G video www-data
+fi
 
 #########################################################################################
 # Record current state of emoncms settings.php
 echo
-current_settings_md5="$(/home/pi/emonpi/./md5sum.py /var/www/emoncms/settings.php)"
+current_settings_md5="$(/home/$username/emonpi/./md5sum.py /var/www/emoncms/settings.php)"
 echo "current settings.php md5: $current_settings_md5"
 
-current_default_settings_md5="$(/home/pi/emonpi/md5sum.py /var/www/emoncms/default.emonpi.settings.php)"
+current_default_settings_md5="$(/home/$username/emonpi/md5sum.py /var/www/emoncms/default.emonpi.settings.php)"
 echo "Default settings.php md5: $current_default_settings_md5"
 
 #########################################################################################
 
 # Pulling in latest Emoncms changes
 echo
-echo "git pull /var/www/emoncms"
+echo "Checking status of /var/www/emoncms git repository"
 cd /var/www/emoncms
-git branch
-git status
-git pull
+branch=$(git branch | grep \* | cut -d ' ' -f2)
+echo "- git branch: $branch"
+changes=$(git diff-index --quiet HEAD --)
+if $changes; then
+    echo "- no local changes"
+    echo "- running: git pull origin $branch"
+    echo
+    git pull origin $branch
+else
+    echo "- changes"
+fi
 
 #########################################################################################
 # check to see if user has modifed settings.php and if update is need. Auto apply of possible
 echo
-new_default_settings_md5="$(/home/pi/emonpi/md5sum.py /var/www/emoncms/default.emonpi.settings.php)"
+new_default_settings_md5="$(/home/$username/emonpi/md5sum.py /var/www/emoncms/default.emonpi.settings.php)"
 echo "NEW default settings.php md5: $new_default_settings_md5"
-
 
 if [ "$current_default_settings_md5" == "$current_settings_md5" ]; then
   echo "settings.php has NOT been user modifed"
@@ -135,146 +170,153 @@ if [ "$new_default_settings_md5" != "$current_default_settings_md5" ]; then
     echo "**ERROR: unable to autoupdate settings.php since user changes are present, manual review required**"
   fi
 else
- echo "settings.php not updated"
+  echo "settings.php not updated"
 fi
+echo
 #########################################################################################
-
+echo "=========================================="
+echo "UPDATING EMONCMS MODULES"
+echo "=========================================="
 echo
+# Update modules installed directly in the Modules folder
+for module in "nodes" "app" "config" "wifi" "dashboard" "graph" "device"; do
 
-if [ -d /var/www/emoncms/Modules/nodes ]; then
-  echo "git pull /var/www/emoncms/Modules/nodes"
-  cd /var/www/emoncms/Modules/nodes
-  git status
-  git branch
-  git pull
-fi
-
-echo
-
-echo "git pull /var/www/emoncms/Modules/app"
-cd /var/www/emoncms/Modules/app
-git branch
-git status
-git pull
-git checkout stable
-
-echo
-
-echo "git pull /var/www/emoncms/Modules/config"
-cd /var/www/emoncms/Modules/config
-git branch
-git status
-git pull
-git checkout stable
-
-echo
-
-echo "git pull /var/www/emoncms/Modules/wifi"
-cd /var/www/emoncms/Modules/wifi
-git branch
-git status
-git pull
-git checkout stable
-
-echo "git pull /var/www/emoncms/Modules/dashboard"
-cd /var/www/emoncms/Modules/dashboard
-git status
-git pull
-git checkout stable
-
-echo
-
-if [ -d /var/www/emoncms/Modules/graph ]; then
-  echo "git pull /var/www/emoncms/Modules/graph"
-  cd /var/www/emoncms/Modules/graph
-  git branch
-  git status
-  git pull
-  git checkout stable
-else
-  echo "Installing Emoncms graph module https://github.com/emoncms/graph"
-  cd /var/www/emoncms/Modules
-  git clone https://github.com/emoncms/graph
-fi
-
-echo
-
-if [ -d /home/pi/postprocess ]; then
-  echo "git pull /home/pi/postprocess"
-  cd /home/pi/postprocess
-  sudo chmod 777 .git -R
-  git checkout emonpi
-  git pull
-  ln -sf /home/pi/postprocess/postprocess-module /var/www/emoncms/Modules/postprocess
-else
-  echo "git clone https://github.com/emoncms/postprocess"
-  cd /home/pi
-  git clone -b emonpi https://github.com/emoncms/postprocess
-  cd /home/pi/postprocess
-  git checkout emonpi
-fi
-
-if [ -d /home/pi/sync ]; then
-  echo "git pull /home/pi/sync"
-  cd /home/pi/sync
-  git checkout master
-  git pull
-  ln -sf /home/pi/sync/sync-module /var/www/emoncms/Modules/sync
-else
-  echo "git clone https://github.com/emoncms/sync"
-  cd /home/pi
-  git clone https://github.com/emoncms/sync
-  cd /home/pi/sync
-  git checkout master
-  ln -sf /home/pi/sync/sync-module /var/www/emoncms/Modules/sync
-fi
-
-if [ -d /var/www/emoncms/Modules/device ]; then
-  echo "git pull /var/www/emoncms/Modules/device"
-  cd /var/www/emoncms/Modules/device
-  git checkout master
-  git pull
-else
-  echo "git clone https://github.com/emoncms/device"
-  cd /var/www/emoncms/Modules
-  git clone https://github.com/emoncms/device
-  cd /var/www/emoncms/Modules/device
-  git checkout master
-fi
-
-
-if [ -d /home/pi/backup ]; then
-  echo "git pull /home/pi/backup"
-  cd /home/pi/backup
-  git branch
-  git status
-  git pull
-  git checkout stable
-else
-  echo "Installing Emoncms backup module from  https://github.com/emoncms/backup"
-  cd /home/pi
-  git clone https://github.com/emoncms/backup
-  cd /home/pi/backup
-  git checkout stable
-  ln -s /home/pi/backup/backup/ /var/www/emoncms/Modules/backup
-  echo "Restarting apache web-server"
-  sudo service apache2 restart
-fi
-
-# Install emoncms-setup module (symlink from emonpi repo)
-if [ -d /home/pi/emonpi/emoncms-setup ] && [ ! -d /var/www/emoncms/Modules/setup ]; then
-  echo "Installing emoncms/emonPi setup module: symlink from ~/emonpi/emoncms-setup"
-  ln -s /home/pi/emonpi/emoncms-setup /var/www/emoncms/Modules/setup
-else
-  if [ ! -d /home/pi/emonpi/emoncms-setup ]; then
-    echo "Cannot find emoncms-setup module, please update ~/emonpi repo"
+  echo "------------------------------------------"
+  echo "Updating $module module"
+  echo "------------------------------------------"
+  if [ -d /var/www/emoncms/Modules/$module ]; then
+    cd /var/www/emoncms/Modules/$module
+    branch=$(git branch | grep \* | cut -d ' ' -f2)
+    echo "- git branch: $branch"
+    changes=$(git diff-index --quiet HEAD --)
+    if $changes; then
+        echo "- no local changes"
+        echo "- running: git pull origin $branch"
+        echo
+        git pull origin $branch
+    else
+        echo "- changes"
+    fi
+  else
+    echo "$module module does not exist"
   fi
-fi
+  echo
+done
 
+# Update modules installed in the home/user folder
+for module in "postprocess" "sync" "backup"; do
+
+  echo "------------------------------------------"
+  echo "Updating $module module"
+  echo "------------------------------------------"
+  if [ -d /home/$username/$module ]; then
+    cd /home/$username/$module
+    branch=$(git branch | grep \* | cut -d ' ' -f2)
+    echo "- git branch: $branch"
+    changes=$(git diff-index --quiet HEAD --)
+    if $changes; then
+        echo "- no local changes"
+        echo "- running: git pull origin $branch"
+        echo
+        git pull origin $branch
+        # ln -sf /home/$username/$module/$module-module /var/www/emoncms/Modules/$module
+    else
+        echo "- changes"
+    fi
+  else
+    echo "$module module does not exist"
+  fi
+  echo
+done
+#########################################################################################
+# Automatic installation of new modules if they dont already exist
+echo "=========================================="
+echo "AUTO INSTALL EMONCMS MODULES"
+echo "=========================================="
+
+# Direct installation in Modules folder
+for module in "graph" "device"; do
+  if ! [ -d /var/www/emoncms/Modules/$module ]; then
+    echo "- Installing Emoncms $module module https://github.com/emoncms/$module"
+    cd /var/www/emoncms/Modules
+    git clone https://github.com/emoncms/$module
+    cd /var/www/emoncms/Modules/$module
+    if [ `git branch --list stable` ]; then
+       echo "-- git checkout stable"
+       git checkout stable
+    fi
+  else
+    echo "- $module module already installed"
+  fi
+done
+
+# Direct installation in Modules folder
+for module in "postprocess" "sync" "backup"; do
+  if ! [ -d /home/$username/$module ]; then
+    echo
+    echo "- Installing Emoncms $module module https://github.com/emoncms/$module"
+    cd /home/$username
+    git clone https://github.com/emoncms/$module
+    ln -s /home/$username/$module/$module-module /var/www/emoncms/Modules
+    cd /home/$username/$module/$module-module
+    if [ `git branch --list stable` ]; then
+       echo "-- git checkout stable"
+       git checkout stable
+    fi
+    echo
+  else
+    echo "- $module module already installed"
+  fi
+done
 echo
+#########################################################################################
+sudo service apache2 restart
 
+if [ "$env_pi" = "1" ]; then 
+  # Install emoncms-setup module (symlink from emonpi repo)
+  if [ -d /home/$username/emonpi/emoncms-setup ] && [ ! -d /var/www/emoncms/Modules/setup ]; then
+    echo "Installing emoncms/emonPi setup module: symlink from ~/emonpi/emoncms-setup"
+    ln -s /home/$username/emonpi/emoncms-setup /var/www/emoncms/Modules/setup
+  else
+    if [ ! -d /home/$username/emonpi/emoncms-setup ]; then
+      echo "Cannot find emoncms-setup module, please update ~/emonpi repo"
+    fi
+  fi
+  echo
+fi
 ################################################################################################
-for service in "mqtt_input" "feedwriter" "service-runner"; do
+# Removal of services
+################################################################################################
+echo "=========================================="
+echo "SERVICES"
+echo "=========================================="
+# 6th Feb 2019: mqtt_input renamed to emoncms_mqtt
+for service in "mqtt_input"; do
+
+  if [ -f /etc/init.d/$service ]; then
+    echo "removing initd $service service"
+    sudo /etc/init.d/$service stop
+    sudo rm /etc/init.d/$service
+  fi
+
+  if [ -L /lib/systemd/system/$service.service ] || [ -f /lib/systemd/system/$service.service ]; then
+    echo "Removing $service.service"
+    sudo systemctl stop $service.service
+    sudo systemctl disable $service.service
+    sudo rm /lib/systemd/system/$service.service
+    sudo systemctl daemon-reload
+  fi
+
+  # if the service still exists in /etc then remove it
+  if [ -L /etc/systemd/system/$service.service ] || [ -f /etc/systemd/system/$service.service ]; then
+    echo "Removing $service.service from /etc/systemd/system"
+    sudo rm /etc/systemd/system/$service.service
+  fi
+done
+################################################################################################
+# Installation or correction of services
+################################################################################################
+for service in "emoncms_mqtt" "feedwriter" "service-runner"; do
 
   if [ -d /etc/systemd ] && [ -f /var/www/emoncms/scripts/services/$service/$service.service ]; then
     if [ -f /etc/init.d/$service ]; then
@@ -314,42 +356,39 @@ for service in "mqtt_input" "feedwriter" "service-runner"; do
     fi
   fi
 done
+echo "------------------------------------------"
+
 ################################################################################################
 ## Don't overwrite settings unless required (un comment if required)
 # echo "Copy new default.emonpi.settings.php to settings.php & make backup old.emonpi.settings.php"
 # sudo cp /var/www/emoncms/settings.php /var/www/emoncms/old.settings.php
 # sudo cp /var/www/emoncms/default.emonpi.settings.php /var/www/emoncms/settings.php
-
-echo
-
-echo "Update Emoncms database"
-php /home/pi/emonpi/emoncmsdbupdate.php
-
-echo
+if [ "$env_pi" = "1" ]; then 
+  echo "Update Emoncms database"
+  php /home/$username/emonpi/emoncmsdbupdate.php
+  echo
+fi
 
 echo "Restarting Services..."
-sudo /etc/init.d/emonhub restart
-sudo /etc/init.d/feedwriter restart
 
+for service in "feedwriter" "mqtt_input" "emoncms_mqtt" "emoncms-nodes-service" "emonhub" "openhab"; do
+  if [ -f /lib/systemd/system/$service.service ]; then
+    echo "- sudo systemctl restart $service.service"
+    sudo systemctl restart $service.service
+    state=$(systemctl show $service | grep ActiveState)
+    echo "--- $state ---"
+  elif [ -f /etc/init.d/$service ]; then
+    echo "- sudo /etc/init.d/$service restart"
+    sudo /etc/init.d/$service restart
+  fi
+done
 echo
-if [ -f /etc/init.d/emoncms-nodes-service ]; then
-  sudo /etc/init.d/emoncms-nodes-service restart
-fi
-
-echo
-if [ -f /etc/init.d/openhab ]; then
-  sudo /etc/init.d/openhab restart
-fi
-
-echo
-if [ -f /etc/init.d/mqtt_input ]; then
-  sudo /etc/init.d/mqtt_input start
-  sleep 1
-  sudo /etc/init.d/mqtt_input restart
-else
-  sudo systemctl restart mqtt_input.service
+if [ "$env_pi" = "1" ]; then 
+  echo "set log rotate config owner to root"
+  sudo chown root:root /etc/logrotate.conf
 fi
 echo
-echo "set log rotate config owner to root"
-sudo chown root:root /etc/logrotate.conf
-echo "Restarting Services..."
+echo "------------------------------------------"
+echo "Emoncms update script complete"
+echo "------------------------------------------"
+
